site_name: Marxism-DIY
site_url: https://marxismdiy.gitbook.io
theme:
  name: material
  palette:

    - 
      scheme: slate
      primary: pink
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      primary: pink
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode